name: private action workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions-sauron/sauron-1680396443151_9c29e8dc-4e26-42a7-9438-6b126bc91c7f-private-action@main
